/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...pathMatch]': RouteRecordInfo<'/[...pathMatch]', '/:pathMatch(.*)', { pathMatch: ParamValue<true> }, { pathMatch: ParamValue<false> }>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/AppHome': RouteRecordInfo<'/AppHome', '/AppHome', Record<never, never>, Record<never, never>>,
    '/Example': RouteRecordInfo<'/Example', '/Example', Record<never, never>, Record<never, never>>,
    '/ExampleParams[email]': RouteRecordInfo<'/ExampleParams[email]', '/ExampleParams:email', { email: ParamValue<true> }, { email: ParamValue<false> }>,
    '/ModelPage': RouteRecordInfo<'/ModelPage', '/ModelPage', Record<never, never>, Record<never, never>>,
    '/register/[email]': RouteRecordInfo<'/register/[email]', '/register/:email', { email: ParamValue<true> }, { email: ParamValue<false> }>,
    '/Rules': RouteRecordInfo<'/Rules', '/Rules', Record<never, never>, Record<never, never>>,
    '/TOS': RouteRecordInfo<'/TOS', '/TOS', Record<never, never>, Record<never, never>>,
  }
}
